[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libxml2", "libxslt", "zlib"]

[phases.install]
cmds = ["python -m pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python main.py"
